# Generated by Django 4.1.5 on 2023-02-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreContacto', models.CharField(max_length=50)),
                ('emailContacto', models.CharField(max_length=50)),
                ('mensajeContacto', models.CharField(max_length=250)),
            ],
        ),
    ]
